Feat/product page
alex4code/fake-burrberry-frontend pull request #1
Opened 2017-08-01 07:26 UTC by alex4code

2017-08-01 12:05 UTC, evgenyrodionov commented
https://rawgit.com/alex4code/fake-burrberry-frontend/feat/product-page/index.html

![image](https://user-images.githubusercontent.com/775692/28824436-9198dc56-76ca-11e7-9488-859303d5e43f.png)

????
![image](https://user-images.githubusercontent.com/775692/28824449-a33cda84-76ca-11e7-8bfe-667d6d5009e7.png)
![image](https://user-images.githubusercontent.com/775692/28824455-b234c740-76ca-11e7-871a-f309532ac5fe.png)
![image](https://user-images.githubusercontent.com/775692/28824461-ba129c4e-76ca-11e7-986f-debd4814e9da.png)
![image](https://user-images.githubusercontent.com/775692/28824470-c27dccc8-76ca-11e7-8e8f-d2aaaf633758.png)

2017-08-01 12:05 UTC, imevro requested changes
фикси дизайн

нейминг не по кодгайду

2017-08-01 18:10 UTC, evgenyrodionov commented
Тут слишком жирный шрифт
![image](https://user-images.githubusercontent.com/775692/28839818-8d5250ae-76fd-11e7-9459-aba5ae7fe96d.png)

Тут бордер не того цвета у черной кнопки и со шрифтом что-то
![image](https://user-images.githubusercontent.com/775692/28839852-a504970c-76fd-11e7-846d-7e3f6f517055.png)

![image](https://user-images.githubusercontent.com/775692/28839878-b66e7922-76fd-11e7-8bb2-9aa977a6204c.png)

line-height
![image](https://user-images.githubusercontent.com/775692/28839886-c227bb8e-76fd-11e7-9f48-ca779400680e.png)

![image](https://user-images.githubusercontent.com/775692/28839893-cbec8492-76fd-11e7-85ff-d1d96b9abc37.png)

2017-08-01 18:12 UTC, imevro requested changes
со шрифтами проблемы + кодгайд нарушен (4 пробела вместо 2, например)

2017-08-02 07:18 UTC, alex4code commented
- Пофиксил шрифты
- Исправил отступы 
- Отрефакторил html - постарался сделать меньше вложенности.
- Добавил фавикон
-  Description и Shipping & returns обернул в button

2017-08-02 10:39 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28870107-b969bb20-7787-11e7-9224-a4cb049da92c.png)
![image](https://user-images.githubusercontent.com/775692/28870111-c0fbe6b0-7787-11e7-98c8-5d0e0473b04e.png)
![image](https://user-images.githubusercontent.com/775692/28870118-c7ceb396-7787-11e7-9a56-257fe8c31bc3.png)
![image](https://user-images.githubusercontent.com/775692/28870130-d1b50f90-7787-11e7-9021-88437da193cf.png)
![image](https://user-images.githubusercontent.com/775692/28870145-dab719f8-7787-11e7-9abb-d54b0235805f.png)
![image](https://user-images.githubusercontent.com/775692/28870154-e2bdba3a-7787-11e7-9af4-2611330bb3ee.png)
![image](https://user-images.githubusercontent.com/775692/28870160-e9a3f51c-7787-11e7-9c52-623c88e272f1.png)

2017-08-02 10:39 UTC, imevro requested changes
↑

2017-08-02 19:20 UTC, evgenyrodionov commented
Саш, ты коммитнул после запроса ревью, поэтому я хз закончил ты работу или нет

2017-08-02 19:20 UTC, evgenyrodionov commented
макет визуально норм

2017-08-03 14:34 UTC, alex4code commented
Сделал планшет,  но какие то траблы с  кнопками : "выбор размера" и "найти в магазине" мутняк, вроде размеры по макету((

2017-08-03 20:16 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28941729-9b8a225a-78a1-11e7-986d-22b7c3f0912d.png)

2017-08-03 20:23 UTC, imevro requested changes

2017-08-03 20:23 UTC, evgenyrodionov commented on css/main.scss
> +*,
этим занимается нормалайз, не трогай

2017-08-03 20:23 UTC, evgenyrodionov commented on css/main.scss
> +button {
нельзя глобально срезать

2017-08-03 20:23 UTC, evgenyrodionov commented on css/main.scss
> +@function rem($pixels) {
в чем смысл?

2017-08-03 20:23 UTC, evgenyrodionov commented on css/main.scss
> +.product-slider img {
не вешай на теги

2017-08-03 20:23 UTC, evgenyrodionov commented on index.html
> +<header class="header">
почему по отступам не видно что хедер внесен в бади?

2017-08-03 20:23 UTC, evgenyrodionov commented on index.html
> +            <source media="(min-width:760px)" srcset="images/content/product/tablet-front.jpg 1x,
почему не в ремах

2017-08-03 20:23 UTC, evgenyrodionov commented on index.html
> +      <span class="info-block-arrow-down"></span>
в цсс через афтер

2017-08-03 20:23 UTC, evgenyrodionov commented on index.html
> +          <h2 class="footer-mnu-title">Our company</h2>
footer-mnu? экономишь на байтах?

2017-08-04 18:12 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28981212-8fd04d82-7959-11e7-89fb-342a7c3ae957.png)

2017-08-05 10:03 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28994762-87304594-79de-11e7-855d-23d9ed12730e.png)

2017-08-05 10:07 UTC, imevro requested changes

2017-08-05 10:07 UTC, evgenyrodionov commented on index.html
> +             is a tightly woven and breathable fabric that protects against wind and rain.<br> Raglan sleeves and a
без бров

2017-08-05 14:58 UTC, imevro approved these changes

2017-08-06 07:35 UTC, merged

2017-08-06 07:36 UTC, evgenyrodionov commented
Переключаешься в мастер, делаешь `git pull origin master --rebase`, новые бранчи от этого мастера