Feat/product page react
alex4code/fake-burrberry-frontend pull request #2
Opened 2017-08-09 17:01 UTC by alex4code

2017-08-09 18:24 UTC, imevro requested changes
Проверял, потом увидел что ты не закончил, остановился. Не кидай пуллреквест пока полностью не закончишь.

Что собрал:
- Нормальные manifest.json и package.json
- Тайтлы через react-helmet
- Функции — тупым компонентам, классы — рабочим

2017-08-09 18:24 UTC, imevro commented on src/App.js
> +const linksForMore = [{href:'/',title: 'Men’s Black Trench Coats'},{href:'/',title: 'Men’s Short Trench Coats'},{href:'/',title: 'Men’s Long Trench Coats'}];
во-первых, разделяй пустыми строками импорты, функции, константы

2017-08-09 18:24 UTC, imevro commented on src/App.js
> +const linksForMore = [{href:'/',title: 'Men’s Black Trench Coats'},{href:'/',title: 'Men’s Short Trench Coats'},{href:'/',title: 'Men’s Long Trench Coats'}];
во-вторых, убери это

2017-08-09 18:24 UTC, imevro commented on src/App.js
> +const title = 'Long Cotton Gabardine Car Coat | Men - Burberry';
и это

2017-08-09 18:24 UTC, imevro commented on src/App.js
> +const description =  'Blending the lines between style and function, a reversible car coat in English-woven, showerproof cotton gabardine and Donegal wool tweed.';
и это

2017-08-09 18:24 UTC, imevro commented on src/App.js
> +        <More title="More for you" links={linksForMore}/>
зачем тайтл передавать пропом?

2017-08-09 18:24 UTC, imevro commented on src/Footer/Footer.js
> +const costomerServiceLinks = [
XML декларативнее чем массив с объектами

2017-08-10 18:02 UTC, imevro requested changes
и поставь преттир, ужасное форматирование кода

2017-08-10 18:02 UTC, evgenyrodionov commented on src/App.js
> +  const App = styled.div`
1) это должно быть повешено на бади
2) зачем const App засовывать в рендер-функцию?

2017-08-10 18:02 UTC, evgenyrodionov commented on src/Footer/Help.js
> +  const Title = styled.h2 `
вынеси стайлед-компоненты за пределы рендера

2017-08-10 18:02 UTC, evgenyrodionov commented on src/Footer/Help.js
> +      <Link href="javascript:void(0);">Find out more and contact us</Link>
убери этот джаваскрипт воид

2017-08-10 18:02 UTC, evgenyrodionov commented on src/Footer/Menu.js
> +    display: block;
что тут с отступами стало

2017-08-10 18:02 UTC, evgenyrodionov commented on src/Footer/index.js
> +      <div className="footer-links">
откуда класснейм

2017-08-10 18:02 UTC, evgenyrodionov commented on src/More/index.js
> +        <Link href="javascript:void(0);">Men’s Black Trench Coats</Link>
почему 4 пробела

2017-08-10 18:02 UTC, evgenyrodionov commented on src/More/index.js
> +import React from 'react';
почему файл отдельно от продукта лежит

2017-08-10 18:02 UTC, evgenyrodionov commented on src/More/index.js
> +import React from 'react';
нет, я понимаю, но тогда у него тупое название директории

2017-08-10 18:02 UTC, evgenyrodionov commented on src/More/index.js
> +import React from 'react';
а также зачем он в директории если тут только index, что мешает положить в `src/More.js`

2017-08-10 18:02 UTC, evgenyrodionov commented on src/Product/Delivery.js
> +  const Item = styled.li`
итем — тупой неочевидный нейминг раз
откуда тут списки взялись два

2017-08-10 18:02 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +    this.setState({isOpened: !this.state.isOpened});
https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-08-11 11:29 UTC, imevro requested changes

2017-08-11 11:29 UTC, evgenyrodionov commented on src/Product/Delivery.js
>       display: none;
чтооооо с отступами

2017-08-11 11:29 UTC, evgenyrodionov commented on src/Product/Delivery.js
>      display: block;
и опять

2017-08-11 11:29 UTC, evgenyrodionov commented on src/Product/Delivery.js
>      margin: 0;
и эгейн

2017-08-11 11:29 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +      return {isOpened: !prevState.isOpened}
ПРЕТТИР

2017-08-11 11:29 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +      return {isOpened: !prevState.isOpened}
ФОРМАТ ОН СЭЙВ ТРУ

2017-08-11 11:29 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +      return {isOpened: !prevState.isOpened}
ИНТЕГРЕЙШЕН ВИЗ ЕСЛИНТ ТРУ

2017-08-11 17:28 UTC, imevro requested changes

2017-08-11 17:28 UTC, evgenyrodionov commented on src/Product/Buttons.js
> +      <Button type="button" black>
почитай в телеграфе пункт про дизайн и систему

2017-08-11 17:28 UTC, evgenyrodionov commented on src/Product/Color.js
> +          Color black
это call to action

2017-08-11 17:28 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +    this.setState(function(prevState, props) {
переделай в arrow function — проще выглядит

2017-08-11 17:28 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +    const Info = styled.div`
почему это в рендере?

2017-08-11 17:28 UTC, evgenyrodionov commented on src/Suggest/index.js
> +              price="27 000"
цену числом передавай + react-intl воткни

2017-08-11 17:28 UTC, evgenyrodionov commented on src/Suggest/index.js
> +            <SuggestItem
итем плохой слишком общий неочевидный нейминг

2017-08-12 11:38 UTC, imevro requested changes

2017-08-12 11:38 UTC, evgenyrodionov commented on src/Product/ColorButton.js
> +    >{`Color ${props.name}`}</Button>
можно просто `>Color {props.name}</`

2017-08-12 11:38 UTC, evgenyrodionov commented on src/Product/InfoBlock.js
> +  & > p {
а зачем селектор >?

2017-08-12 11:38 UTC, evgenyrodionov commented on src/Suggest/index.js
> +            <SuggestItem
И?

2017-08-12 16:55 UTC, alex4code commented
Зафакапил, десктоп не перенес в отдельную ветку, каюсь((

2017-08-12 20:02 UTC, imevro requested changes

2017-08-12 20:02 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "fake burrberry frontend",
плохое имя для магазина

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Product/Color.js
> +        {`Colour: `}
а зачем тут так?

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Product/Delivery.js
> +const Default = ({ children }) =>
что это делает тут при наличии коммон респонсив

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Product/Header.js
> +                <SliderItem
итем — тупой нейминг

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Product/InfoImage.js
> +width: 100%;
что с отступами

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Product/index.js
> +            <InfoImage nameItem="2" margin="2" />
что за неймитем?

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Product/index.js
> +            <InfoImage nameItem="2" margin="2" />
и убери эти марджины, сделай через nth-child

2017-08-12 20:02 UTC, evgenyrodionov commented on src/Suggest/index.js
> +            <SuggestItem
опять итем

2017-08-12 20:02 UTC, evgenyrodionov commented on src/common/responsive.js
> +export const Md = ({ children }) =>
сделай MdOnly / XsOnly если так оно работает

2017-08-13 11:20 UTC, imevro requested changes
исправишь — напиши в телеграм

2017-08-13 11:20 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "burberry shop",
Почему так наплевательски выглядит?

2017-08-13 11:20 UTC, evgenyrodionov commented on src/Footer/Help.js
> +    <XsOnly>
это нужно делать не в самом компоненте, а там, где ты его используешь

2017-08-13 17:43 UTC, imevro approved these changes

2017-08-13 17:44 UTC, merged