Feat/product list react
alex4code/fake-burrberry-frontend pull request #5
Opened 2017-08-17 13:18 UTC by alex4code

2017-08-17 13:23 UTC, alex4code commented
Я просто этот ветку наследовал от feat/ci  по этому и конфликты скорей всего, я попробовал через чери пик но что то там конфликтов не меньше и каждый комит который переноситься нужно было разрешать я просто слил то что в мастере на рабочую ветку, разрезолвил проверил - все ок, надеюсь так можно?

2017-08-17 20:25 UTC, alex4code commented
https://build-uqhekqicwn.now.sh  - залил

2017-08-18 16:39 UTC, imevro requested changes
плохо со стилем кода, поставь преттир

2017-08-18 16:39 UTC, evgenyrodionov commented on src/App.jsx
> +import { Xl } from './common/responsive';
если респонсив это компонент, то почему это не отражено в названии

2017-08-18 16:39 UTC, evgenyrodionov commented on src/App.jsx
> +              <title>Long Cotton Gabardine Car Coat | Men - Burberry</title>
что этот тайтл делает на главной странице?

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Footer/Menu.jsx
> +    padding-bottom: 0.0625rem;
откуда 4 пробела взялись в отступах

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Footer/Menu.jsx
> +            <Ref to="/">Payment</Ref>
Ref? странный нейминг

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Header/index.jsx
> +  width: 10.375rem;
зачем задавать ширину? достаточно высоту

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +      src: `${imageUrl}${props.src}`,
зачем это хранить в стейте?

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +  handleHover() {
зачем ховером управлять через реакт? чем :hover не помогает?

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +import hartBlack from '../../images/hart_black.svg';
hart? wtf is hart?

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Products/List/Card.jsx
> +import hartBlack from '../../images/hart_black.svg';
зачем два файла если можно красить через цссовский fill?

2017-08-18 16:39 UTC, evgenyrodionov commented on src/Products/List/InfoMenu.jsx
> +    &:last-child {
дело не в ласт-чайлде, тут просто какие-то элементы должны быть справа. Их там будет два, как это сделать в твоей верстке?

2017-08-18 16:40 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/29468471-11b1b2fc-844d-11e7-9154-9bec3b058a15.png)

2017-08-18 16:41 UTC, evgenyrodionov commented
Мыло жёсткое вообще

![image](https://user-images.githubusercontent.com/775692/29468488-2a47dfe4-844d-11e7-9597-542999713e12.png)

2017-08-18 21:02 UTC, alex4code commented
https://build-wgwgexhybr.now.sh

2017-08-18 22:47 UTC, imevro commented
По шрифтам всё очень мимо, перепроверяй

Плюс макет
![image](https://user-images.githubusercontent.com/775692/29480323-35b837ec-8480-11e7-849e-c04fae02efbf.png)
![image](https://user-images.githubusercontent.com/775692/29480331-462e816c-8480-11e7-9d24-380d698dffb0.png)
![image](https://user-images.githubusercontent.com/775692/29480338-5258a756-8480-11e7-984b-7395e21392ab.png)

2017-08-19 08:57 UTC, alex4code commented
https://build-wqyokracmj.now.sh

2017-08-19 11:35 UTC, evgenyrodionov commented
Поправь плз
![image](https://user-images.githubusercontent.com/775692/29486318-8ed918a8-84eb-11e7-93b5-442399f2f6b6.png)

Шрифты в кнопке View More вообще левые кстати
![image](https://user-images.githubusercontent.com/775692/29486322-9989ee58-84eb-11e7-8d5b-235862029ead.png)

2017-08-19 11:36 UTC, evgenyrodionov commented
Планшет
![image](https://user-images.githubusercontent.com/775692/29486329-cb8dd11c-84eb-11e7-9442-cd6061aec1fa.png)

2017-08-19 11:37 UTC, evgenyrodionov commented
Мобайл

![image](https://user-images.githubusercontent.com/775692/29486332-e035104e-84eb-11e7-9508-f024fa93a059.png)

![image](https://user-images.githubusercontent.com/775692/29486336-e70dc064-84eb-11e7-8e16-333dd8cbf259.png)

2017-08-19 16:53 UTC, alex4code commented
https://build-fydaklhjfe.now.sh

2017-08-19 20:31 UTC, evgenyrodionov commented
Бордер-боттом, а не текст-декорейшен
![image](https://user-images.githubusercontent.com/775692/29489961-5f942826-8536-11e7-8926-ea349de14080.png)

Нет черного цвета
![image](https://user-images.githubusercontent.com/775692/29489963-6d574c9a-8536-11e7-834c-cd1fb21a323b.png)

2017-08-19 20:44 UTC, imevro requested changes

2017-08-19 20:44 UTC, evgenyrodionov commented on src/App.jsx
> +import Menu from './common/Menu';
почему это не в хедере

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Footer/Menu.jsx
> +    padding-bottom: 0.0625rem;
зачем ты выебал отступы

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Header/Logo.jsx
> +const NavLink = styled(Link)`
странный нейминг, почему именно нав?

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Header/index.jsx
> +                <Country>Shopping in: United Kingdom (£)</Country>
Кантри что

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/List/Category.jsx
> +export default function Categoty(props) {
опечатка тут

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/List/Category.jsx
> +    if (i < 4) {
убери этот костыль

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/List/Category.jsx
> +    if (i < 4) {
везде одинаковое кол-во карточек должно быть

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/List/Category.jsx
> +  title: 'title',
странный тайтл

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/List/InfoMenu.jsx
> +    & > button {
нет же

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    <div className="container">
почему бы не засунуть все 3 элемента в контейнер

2017-08-19 20:44 UTC, evgenyrodionov commented on src/Products/Show/index.jsx
> +import Suggest from '../../Suggest/index';
откуда индекс взялся в импорте, зачем

2017-08-19 20:44 UTC, evgenyrodionov commented on src/common/Menu.jsx
> +        <Link activeStyle={linkActiveStyle} to="/women">
делай через эктивкласснейм

2017-08-19 23:49 UTC, alex4code commented
https://build-fxcuagkidn.now.sh

2017-08-20 09:32 UTC, imevro approved these changes

2017-08-20 09:32 UTC, merged