Feat/ux
alex4code/fake-burrberry-frontend pull request #7
Opened 2017-08-26 16:33 UTC by alex4code

2017-08-26 16:35 UTC, alex4code commented
Посмотри пожалуйста.
https://build-nplcoqmcjh.now.sh
Сделал лайк, дропдаун, размеры и цвет, а также выбор местоположения в хедере, все делал без плагинов.

2017-08-29 16:27 UTC, alex4code commented
https://build-lalzprouwf.now.sh
лайк, дропдаун, размеры и цвет, а также выбор местоположения в хедере, все делал без плагинов.

2017-08-29 19:10 UTC, evgenyrodionov commented
Во-первых, РАШН ФЕДЕРАШЕН, во-вторых,

![image](https://user-images.githubusercontent.com/775692/29839424-d459760c-8d06-11e7-881b-3e0d93d33ffb.png)

2017-08-29 19:11 UTC, evgenyrodionov commented
Иконки забавно красятся
![image](https://user-images.githubusercontent.com/775692/29839450-e82d5af4-8d06-11e7-9b85-441fa08b6fd3.png)

![men s clothing burberry 2017-08-29 22-10-49](https://user-images.githubusercontent.com/775692/29839458-ef97621c-8d06-11e7-9782-a7ff109e8ad7.png)

2017-08-29 19:11 UTC, evgenyrodionov commented
Чё-то страница товара развалилась

2017-08-29 19:25 UTC, imevro requested changes

2017-08-29 19:25 UTC, evgenyrodionov commented on src/App.jsx
> +let language = 'en';
без мутабельности

2017-08-29 19:25 UTC, evgenyrodionov commented on src/App.jsx
> +  handelLocalChange(e) {
local?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/App.jsx
> +  handelLocalChange(e) {
handel?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/App.jsx
> +                hendelLocal={this.handelLocalChange}
hendelLocal??

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Footer/FooterSelect.jsx
> +/* eslint-disable react/forbid-prop-types */
нельзя выключать правила без согласования со мной это раз

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Footer/FooterSelect.jsx
> +/* eslint-disable react/forbid-prop-types */
зачем у файла префикс Footer если ты и так в директории футер два

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Footer/FooterSelect.jsx
> +    this.state = { value: this.props.local };
зачем это класть в локальный стейт?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Footer/index.jsx
> +    name: 'Russian Federation',
чем этот массив отличается от верхнего

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Footer/index.jsx
> +          {...props}
нет, явное лучше неявного

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Footer/index.jsx
> +          values={shippingCountry}
плохой нейминг, что за вэльюс

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Header/ContrySelect.jsx
> +const Countries = [
это компонент? раз

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Header/ContrySelect.jsx
> +const Countries = [
почему это сверху не может приходить два

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Header/ContrySelect.jsx
> +              >{`Shopping in: ${contry.name}`}</option>),
а зачем тут интерполяция строк? почему не `Shopping in {country.name}`?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Header/ContrySelect.jsx
> +              >{`Shopping in: ${contry.name}`}</option>),
и почему столько опечаток? country, не contry!

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Header/ContrySelect.jsx
> +  hendelLocal: () => '',
нет

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Header/ContrySelect.jsx
> +  hendelLocal: () => '',
ставь isRequired

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +      <Wrapper isSort={this.props.sort}>
компоненту должно быть похуй сортировка это, выбор категории или размера, у него тупая задача — быть справа

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +      return;
нулевые рётерны это контринтуитивно

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +      this.setState(() => ({ showDropdown: true }));
зачем тут функция в сетстейте?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +    this.state = { showDropdown: false };
ты определись хоть, у тебя булеаны через `is*` идут или нет

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +      this.props.onDropdown(event.target.id);
onDropdown? что onDropdown?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +      this.props.onDropdown(event.target.id);
событие какое? дропдаун?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +      document.addEventListener('click', this.handleClickOutside);
нет нужды создавать эвентлистенер каждый раз, когда можно один

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/Filter.jsx
> +            content content content content content content content content
в каждом дропдауне свой контент вообще-то

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +    this.state = { dropdownEvent: false };
dropdownEvent? что значит этот нейминг?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/Show/Color.jsx
> +    this.onActiveColor = this.onActiveColor.bind(this);
onActiveColor?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/Show/Color.jsx
> +    const id = +e.target.id;
+?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/Show/Header.jsx
> +    this.state = { colorState: '1' };
почему строкой
зачем постфикс стейт у параметра

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/Show/Header.jsx
> +    this.setState(() => ({ colorState: event }));
зачем эвент засовывать в стейт?

2017-08-29 19:25 UTC, evgenyrodionov commented on src/Products/Show/Size.jsx
> +  render() {
ставь отступы между методами

2017-08-29 19:25 UTC, evgenyrodionov commented on src/common/LikeIcon.jsx
> +        <svg
иконку вынеси в отдельный компонент, потому что ее можно будет переиспользовать

2017-08-29 19:25 UTC, evgenyrodionov commented on src/common/LikeIcon.jsx
> +            fill={this.state.isLiked}
зачем подменять значение? филл отвечает за цвет, а ты передаешь булеан

2017-08-31 08:35 UTC, alex4code commented
https://build-acoqjgyuse.now.sh
Пофиксил ошибки

2017-08-31 12:14 UTC, evgenyrodionov commented
Втф

![image](https://user-images.githubusercontent.com/775692/29922608-fa8d278e-8e5e-11e7-8ba9-a847afda6d0d.png)

2017-08-31 12:28 UTC, imevro requested changes
зря убрал работу с локалями

2017-08-31 12:28 UTC, evgenyrodionov commented on src/Footer/Select.jsx
> +    const options = this.props.options;
http://2ality.com/2015/01/es6-destructuring.html

2017-08-31 12:28 UTC, evgenyrodionov commented on src/Products/Card/LikeIcon.jsx
> +          color={this.state.isLiked ? fillColor : 'none'}
почему color, а не fill?

2017-08-31 12:28 UTC, evgenyrodionov commented on src/Products/List/index.jsx
> +  { name: 'Category', content: 'Category content' },
а если мне нужно будет другие компоненты в контент засовывать? чекбоксы, радио, етц?

2017-08-31 12:28 UTC, evgenyrodionov commented on src/Products/Show/Color.jsx
>      this.props.handelColorChange(colors[id].img);
> handelColorChange

2017-08-31 16:56 UTC, alex4code commented
https://build-ldqmxpsgxc.now.sh 
Пофиксил ошибки,

2017-08-31 18:13 UTC, imevro requested changes

2017-08-31 18:13 UTC, evgenyrodionov commented on src/Products/Show/Color.jsx
>      this.props.handelColorChange(colors[id].img);
ПЕРЕИМЕНУЙ

2017-08-31 18:13 UTC, evgenyrodionov commented on src/Products/Show/Color.jsx
>      this.props.handelColorChange(colors[id].img);
СКОЛЬКО МОЖНО ДОПУСКАТЬ ОПЕЧАТКУ

2017-09-01 11:26 UTC, imevro requested changes

2017-09-01 11:26 UTC, evgenyrodionov commented on src/App.jsx
> +    this.state = { localId: 0 };
local → locale

2017-09-01 11:26 UTC, evgenyrodionov commented on src/App.jsx
> +    this.setState(() => ({ localId: id }));
тут не нужна функция

2017-09-01 11:26 UTC, evgenyrodionov commented on src/App.jsx
> +                handelLocalChange={this.handelLocalChange}
# сколько можно писать handel вместо handle


????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? [...]

2017-09-01 11:26 UTC, evgenyrodionov commented on src/Header/Select.jsx
> +    this.state = { selectId: this.props.localId };
зачем это в стейте хранить? либо пропы, либо стейт, иначе рассинхронизация данных — в стейте одно, в пропах другое

2017-09-01 11:26 UTC, evgenyrodionov commented on src/Products/Show/Color.jsx
>    }
ставь отступы между методами

2017-09-02 09:04 UTC, alex4code commented
Пофиксил ошибки, сделал меню - https://avelichko-burberry-fake-shop-for-study-dev.now.sh/

2017-09-02 11:08 UTC, imevro requested changes

2017-09-02 11:08 UTC, evgenyrodionov commented on src/App.jsx
> +  content: '';
куда отступы уехали

2017-09-02 11:08 UTC, evgenyrodionov commented on src/MobileNavigation/Select.jsx
> +  const options = props.options;
http://2ality.com/2015/01/es6-destructuring.html

2017-09-02 11:08 UTC, evgenyrodionov commented on src/MobileNavigation/index.jsx
> +    transform: translateX(${props => (props.isMenuOpened ? '-274px' : '0')});
откуда 4 отступа

2017-09-02 11:08 UTC, evgenyrodionov commented on src/MobileNavigation/index.jsx
> +      isSubMenuOpened: !this.state.isSubMenuOpened,
https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1

2017-09-02 15:54 UTC, alex4code commented
- пофиксил отступы
- использовал деструктурирующее присваивание
- заюзал функцию в 'setState' вместо объекта

https://avelichko-burberry-fake-shop-for-study-dev.now.sh/

2017-09-02 18:41 UTC, evgenyrodionov commented on src/MobileNavigation/Select.jsx
> +  const { options } = props;
ты это можешь делать сразу в параметре функции)

2017-09-02 18:43 UTC, imevro requested changes

2017-09-02 18:43 UTC, evgenyrodionov commented on src/MobileNavigation/index.jsx
> +      categoryId: subSectionIndex }
преттир не отработал?

2017-09-02 19:46 UTC, alex4code commented on src/MobileNavigation/Select.jsx
> +  const { options } = props;
Круто, я не знал что так можно!

2017-09-03 10:49 UTC, imevro approved these changes

2017-09-03 10:49 UTC, merged